# Use this requirements file to install the role

---
roles:
  - name: deploy_python_program
    src: https://github.com/megahomyak/ansible_role_for_python_scripts_deployment.git
    scm: git
    version: master
