---
- name: install python and rsync
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  with_items:
    - python3
    - rsync

- name: deploy the files
  ansible.posix.synchronize:
    src: "{{playbook_dir}}/src/"
    dest: "{{program_sources_path_on_the_remote_host}}"
    delete: yes
  register: files_deploying_result

- name: add preferences to the entry point file
  ansible.builtin.file:
    mode: u+x
    path: "{{entry_point_file_path}}"

- name: install the requirements
  shell: "{{pip_name_or_path}} install -r {{program_sources_path_on_the_remote_host}}/requirements.txt"
  ignore_errors: true

- name: add a systemd unit
  template:
    src: "{{unit_file_template_name}}"
    dest: "{{remote_systemd_units_path}}/{{systemd_unit_name}}"
    mode: 0644
  notify:
    - enable and activate the systemd unit
    - reload the systemd configuration files
  register: systemd_unit_creation_result

- name: restart the systemd unit
  ansible.builtin.systemd:
    name: "{{systemd_unit_name}}"
    state: restarted
  when: systemd_unit_creation_result is changed or files_deploying_result is changed
  tags:
    - restart

- name: stop the systemd unit
  ansible.builtin.systemd:
    name: "{{systemd_unit_name}}"
    state: stopped
  tags:
    - stop
    - never

- name: disable and stop the systemd unit
  ansible.builtin.systemd:
    name: "{{systemd_unit_name}}"
    state: stopped
    enabled: no
  tags:
    - vanish
    - never

- name: remove the systemd unit
  ansible.builtin.file:
    state: absent
    path: "{{remote_systemd_units_path}}/{{systemd_unit_name}}"
  tags:
    - vanish
    - never

- name: remove the sources directory
  ansible.builtin.file:
    state: absent
    path: "{{program_sources_path_on_the_remote_host}}"
  tags:
    - vanish
    - never
